[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
preDeployCommand = "npx prisma db push --schema=prisma/schema.prisma"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
